name: Windows Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Electron App
        run: npx electron-builder --win --x64 --publish always

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: law-firm-windows-build
          path: |
            release/**/*.exe
