name: Windows Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create Git Tag from package.json version
        shell: bash
        env:
          PAT: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          VERSION="v$(node -p "require('./package.json').version")"
          echo "Creating tag $VERSION"

          # Configure Git to use PAT for push
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}

          # Create and push tag
          git tag $VERSION
          git push origin $VERSION

      - name: Build and Publish Electron App
        run: npx electron-builder --win --x64 --publish always

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: law-firm-windows-build
          path: |
            release/**/*.exe
