name: Windows Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create Git Tag from package.json version
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          $version = "v" + (node -p "require('./package.json').version")
          Write-Host "Creating tag $version"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag $version

          # Override the Git remote to use the GitHub PAT
          git remote set-url origin "https://x-access-token:$env:GH_TOKEN@github.com/${{ github.repository }}"

          git push origin $version

      - name: Build and Publish Electron App
        run: npx electron-builder --win --x64 --publish always

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: law-firm-windows-build
          path: |
            release/**/*.exe
